In [102]:
import pandas as pd 
import numpy as np 

corpus = pd.read_csv('dataset.csv').values

In [103]:
corpus

array([[1, 'Colombo', 3, 500.0, '?', 0.25, 'yes'],
       [2, 'Singapore', 2, 1500.0, '0', 0.31, 'yes'],
       [3, 'Singapore', 4, 2000.0, '1', 1.2, 'yes'],
       [4, 'Tokyo', 4300, 1300.0, '0', 0.8, 'no'],
       [5, 'Melbourne', 6, 1.3, '0', 0.5, 'no'],
       [6, 'Singapore', 4, 1800.0, '1', 0.3, 'no'],
       [7, '?', 5, 700.0, '1', 0.4, 'yes']], dtype=object)

In [10]:
type(corpus)

numpy.ndarray

In [107]:
##detect misising values in the data 

symbols = ['?', '*', '#', 'Nan']
complete = []

for row in corpus:
    if set(row) & set(symbols):
        print(row)
        
    else:
        complete.append(row)
        

[1 'Colombo' 3 500.0 '?' 0.25 'yes']
[7 '?' 5 700.0 '1' 0.4 'yes']


In [108]:
complete

[array([2, 'Singapore', 2, 1500.0, '0', 0.31, 'yes'], dtype=object),
 array([3, 'Singapore', 4, 2000.0, '1', 1.2, 'yes'], dtype=object),
 array([4, 'Tokyo', 4300, 1300.0, '0', 0.8, 'no'], dtype=object),
 array([5, 'Melbourne', 6, 1.3, '0', 0.5, 'no'], dtype=object),
 array([6, 'Singapore', 4, 1800.0, '1', 0.3, 'no'], dtype=object)]

In [106]:
complete

array([<built-in function array>, 2, 'Singapore', 2, 1500.0, '0', 0.31,
       'yes', 3, 'Singapore', 4, 2000.0, '1', 1.2, 'yes', 4, 'Tokyo',
       4300, 1300.0, '0', 0.8, 'no', 5, 'Melbourne', 6, 1.3, '0', 0.5,
       'no', 6, 'Singapore', 4, 1800.0, '1', 0.3, 'no'], dtype=object)

In [ ]:
## median to use the range of normality 

In [12]:
import pandas as pd 
import numpy as np 

corpus = pd.read_csv('dataset.csv')
corpus

ID       City  Items   Price Payment   Tax Transaction
0   1    Colombo      3   500.0       ?  0.25         yes
1   2  Singapore      2  1500.0       0  0.31         yes
2   3  Singapore      4  2000.0       1  1.20         yes
3   4      Tokyo   4300  1300.0       0  0.80          no
4   5  Melbourne      6     1.3       0  0.50          no
5   6  Singapore      4  1800.0       1  0.30          no
6   7          ?      5   700.0       1  0.40         yes

In [13]:
items = corpus.iloc[: ,2].values

In [14]:
items

array([   3,    2,    4, 4300,    6,    4,    5], dtype=int64)

# Median to Range of Normality

In [15]:
median = np.median(items)

In [17]:
median

4.0

In [19]:
k =3
cutoff = median * k
lower,upper = median - cutoff, median + cutoff 
lower,upper


(-8.0, 16.0)

In [21]:
for item in items:
    if item< lower or item > upper:
        print(item)

4300


In [22]:
yes_items = corpus[corpus['Transaction'] == 'yes'].iloc[:,2].values 
no_items = corpus[corpus['Transaction'] == 'no'].iloc[:,2].values 

In [23]:
yes_items

array([3, 2, 4, 5], dtype=int64)

In [27]:
#range of normality for the label yes 

yes_median = np.median(yes_items)
yes_cutoff = yes_median * 3 
yeslower, yesupper = yes_median - yes_cutoff, yes_median + yes_cutoff
yeslower,yesupper

(-7.0, 14.0)

In [28]:
#range of normality for the label no

no_median = np.median(no_items)
no_cutoff = no_median * 3 
nolower, noupper = no_median - no_cutoff, no_median + no_cutoff
nolower,noupper


(-12.0, 24.0)

In [29]:
for item in yes_items:
    if item < yeslower or item > yesupper:
        print(item)

In [32]:
for item in no_items:
    if item < nolower or item > noupper:
        print(item)

4300


# Mean Range of Normality 

In [34]:
price = corpus.iloc[:,3].values
price

array([5.0e+02, 1.5e+03, 2.0e+03, 1.3e+03, 1.3e+00, 1.8e+03, 7.0e+02])

In [38]:
mean = np.mean(price)
std = np.std(price)
cutoff = std * 3 
lower, upper = mean - cutoff, mean + cutoff
lower,upper

(-922.0200083496948, 3150.962865492552)

In [37]:
mean, std


(1114.4714285714285, 678.8304789737077)

In [39]:
for p in price:
    if p < lower or p > upper:
        print(p)

# Local Context

In [40]:
yes_price = corpus[corpus['Transaction'] == 'yes'].iloc[:,3].values
yes_price

array([ 500., 1500., 2000.,  700.])

In [41]:
yes_mean = np.mean(yes_price)
yes_std = np.std(yes_price)
yes_cutoff = yes_std * 3 

In [43]:
yes_lower, yes_upper = yes_mean - yes_cutoff, yes_mean + yes_cutoff

In [44]:
yes_lower, yes_upper

(-642.1062159378575, 2992.1062159378575)

# Z SCORES APPROACH

In [45]:
prices = corpus['Price']. values 

In [46]:
price

array([5.0e+02, 1.5e+03, 2.0e+03, 1.3e+03, 1.3e+00, 1.8e+03, 7.0e+02])

In [47]:
from scipy import stats

In [48]:
zcores = stats.zscore(prices)

In [49]:
lower, upper = -3,3 ## come from K 

In [53]:
for zscore in zcores:
    if zscore < lower or zscore > upper:
        print(zscore) #we gud 

# INTERQUATILE RANGE DETECTION

In [60]:
items  = corpus['Items'].values
items

array([   3,    2,    4, 4300,    6,    4,    5], dtype=int64)

In [61]:
q25 = np.percentile(items,25)
q50 = np.percentile(items,50)
q75 = np.percentile(items,75)

q25,q50,q75

(3.5, 4.0, 5.5)

In [62]:
iqr = q75 - q25
iqr

2.0

In [63]:
cutoff = iqr * 3 #k=3 

In [65]:
lower, upper = q25 - cutoff, q75 + cutoff
lower,upper

(-2.5, 11.5)

In [67]:
np.where((items < lower)or(items > upper))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [68]:
np.where(items >upper)

(array([3], dtype=int64),)

In [76]:
np.where(items>upper) or np.where(items<lower)

(array([3], dtype=int64),)

In [172]:
import pandas as pd
corpus = pd.read_csv('dataset.csv')
corpus

ID       City  Items   Price Payment   Tax Transaction
0   1    Colombo      3   500.0       ?  0.25         yes
1   2  Singapore      2  1500.0       0  0.31         yes
2   3  Singapore      4  2000.0       1  1.20         yes
3   4      Tokyo   4300  1300.0       0  0.80          no
4   5  Melbourne      6     1.3       0  0.50          no
5   6  Singapore      4  1800.0       1  0.30          no
6   7          ?      5   700.0       1  0.40         yes

In [133]:
#Mode
cities = corpus['City'].values
cities

array(['Colombo', 'Singapore', 'Singapore', 'Tokyo', 'Melbourne',
       'Singapore', '?'], dtype=object)

In [118]:
from scipy import stats
mode = stats.mode(cities)[0][0]
mode

'Singapore'

In [136]:
corpus['City'] = corpus['City'].replace({'?':'Singapore'})

In [139]:
corpus.head(7)

ID       City  Items   Price Payment   Tax Transaction
0   1    Colombo      3   500.0       ?  0.25         yes
1   2  Singapore      2  1500.0       0  0.31         yes
2   3  Singapore      4  2000.0       1  1.20         yes
3   4      Tokyo   4300  1300.0       0  0.80          no
4   5  Melbourne      6     1.3       0  0.50          no
5   6  Singapore      4  1800.0       1  0.30          no
6   7  Singapore      5   700.0       1  0.40         yes

In [130]:
corpus['City'] = np.where(corpus['City'] == '?', corpus['City'], mode)

In [131]:
corpus.head(6)

ID       City  Items   Price Payment   Tax Transaction
0   1  Singapore      3   500.0       ?  0.25         yes
1   2  Singapore      2  1500.0       0  0.31         yes
2   3  Singapore      4  2000.0       1  1.20         yes
3   4  Singapore   4300  1300.0       0  0.80          no
4   5  Singapore      6     1.3       0  0.50          no
5   6  Singapore      4  1800.0       1  0.30          no

In [143]:
corpus['City'].apply(lambda x: x)

0      Colombo
1    Singapore
2    Singapore
3        Tokyo
4    Melbourne
5    Singapore
6    Singapore
Name: City, dtype: object

# Lambda WAY

In [147]:
corpus['City'].apply(lambda x: x == 'Singapore' if x == '?' else x)

0      Colombo
1    Singapore
2    Singapore
3        Tokyo
4    Melbourne
5    Singapore
6    Singapore
Name: City, dtype: object

In [122]:
corpus.iterrows()

<generator object DataFrame.iterrows at 0x0000027C9412F7B0>

In [148]:
# Median 
items = corpus.iloc[:,2].values
items

array([   3,    2,    4, 4300,    6,    4,    5], dtype=int64)

In [149]:
median = np.median(items)
median

4.0

In [150]:
def isNoisevalue(x):
    if x>1000:
        return True 

In [154]:
new_items =[]
for item in items:
    if isNoisevalue(item):
        new_items.append(median)
    else:
        new_items.append(item)

In [155]:
new_items

[3, 2, 4, 4.0, 6, 4, 5]

In [158]:
corpus.head(7)

ID       City  Items   Price Payment   Tax Transaction
0   1    Colombo      3   500.0       ?  0.25         yes
1   2  Singapore      2  1500.0       0  0.31         yes
2   3  Singapore      4  2000.0       1  1.20         yes
3   4      Tokyo   4300  1300.0       0  0.80          no
4   5  Melbourne      6     1.3       0  0.50          no
5   6  Singapore      4  1800.0       1  0.30          no
6   7  Singapore      5   700.0       1  0.40         yes

In [179]:
import pandas as pd
corpus = pd.read_csv('dataset.csv')
corpus

ID       City  Items   Price Payment   Tax Transaction
0   1    Colombo      3   500.0       ?  0.25         yes
1   2  Singapore      2  1500.0       0  0.31         yes
2   3  Singapore      4  2000.0       1  1.20         yes
3   4      Tokyo   4300  1300.0       0  0.80          no
4   5  Melbourne      6     1.3       0  0.50          no
5   6  Singapore      4  1800.0       1  0.30          no
6   7          ?      5   700.0       1  0.40         yes

In [180]:
corpus['Items'] = corpus['Items'].apply(lambda x : x == '4' if x > 1000 else x) 

In [182]:
corpus['Items'] = corpus['Items'].replace({False:'4'})

In [183]:
corpus.head(5)

ID       City Items   Price Payment   Tax Transaction
0   1    Colombo     3   500.0       ?  0.25         yes
1   2  Singapore     2  1500.0       0  0.31         yes
2   3  Singapore     4  2000.0       1  1.20         yes
3   4      Tokyo     4  1300.0       0  0.80          no
4   5  Melbourne     6     1.3       0  0.50          no

In [171]:
corpus.dtypes

ID               int64
City            object
Items           object
Price          float64
Payment         object
Tax            float64
Transaction     object
dtype: object